config/routes.rb
Rails.application.routes.draw do
  resources :states
  resources :bugs
  get 'search', to: 'search#search'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bug.rb
require 'elasticsearch/model'
class Bug < ApplicationRecord
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  belongs_to :state
  validates_presence_of :status, :priority, :application_token
  validates_inclusion_of :status, in: [ 'new', 'in_progress', 'closed'], message: 'Status must be new, in_progress or closed'
  validates_inclusion_of :priority, in: [ 'minor', 'major', 'critical'], message: 'Status must be minor, major or critical'
end
Bug.import force: true

app/models/state.rb
class State < ApplicationRecord
  has_one :bug
  validates_presence_of :device, :os, :memory, :storage
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  skip_before_action :verify_authenticity_token
end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController
  before_action :set_bug, only: [ :edit, :update, :destroy]

  # GET /bugs
  # GET /bugs.json
  def index
    @bugs = Bug.where(application_token: request.headers["HTTP_APPLICATION_TOKEN"])
  end

  # GET /bugs/1
  # GET /bugs/1.json
  def show
    @bug = Bug.find_by(number: params[:id], application_token: request.headers["HTTP_APPLICATION_TOKEN"])
  end

  # GET /bugs/new
  def new
    @bug = Bug.new
  end


  # POST /bugs
  # POST /bugs.json
  def create
    @bug = Bug.new(bug_params)
    set_number
    respond_to do |format|
      if @bug.save
        format.html { render :index }
        format.json { render json: @bug, status: :ok}
      else
        format.html { render :new }
        format.json { render json: @bug.errors, status: :unprocessable_entity }
      end
    end
  end



  private
  # Use callbacks to share common setup or constraints between actions.
  def set_bug
    @bug = Bug.find(params[:id])
  end

  def set_number
    @bugs = Bug.where(application_token: params[:bug][:application_token])
    if !@bugs.empty?
      @bug.number = @bugs.maximum('number') + 1
    else
      @bug.number = 1;
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def bug_params
    params.fetch(:bug).permit(:application_token, :number, :status, :priority, :comment, :state_id)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    if params[:q].nil?
      @bugs = []
    else
      @bugs = Bug.search params[:q]
    end
    respond_to do |format|
      format.html
      format.json { render json: @bugs }
    end
  end
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  before_action :set_state, only: [:show, :edit, :update, :destroy]

  # GET /states
  # GET /states.json
  def index
    @states = State.all
  end

  # GET /states/1
  # GET /states/1.json
  def show
  end

  # GET /states/new
  def new
    @state = State.new
  end

  # GET /states/1/edit
  def edit
  end

  # POST /states
  # POST /states.json
  def create
    @state = State.new(state_params)

    respond_to do |format|
      if @state.save
        format.html { redirect_to @state, notice: 'State was successfully created.' }
        format.json { render :show, status: :created, location: @state }
      else
        format.html { render :new }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /states/1
  # PATCH/PUT /states/1.json
  def update
    respond_to do |format|
      if @state.update(state_params)
        format.html { redirect_to @state, notice: 'State was successfully updated.' }
        format.json { render :show, status: :ok, location: @state }
      else
        format.html { render :edit }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /states/1
  # DELETE /states/1.json
  def destroy
    @state.destroy
    respond_to do |format|
      format.html { redirect_to states_url, notice: 'State was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_state
      @state = State.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def state_params
      params.require(:state).permit(:device, :os, :memory, :storage)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bugs_helper.rb
module BugsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/bugs/_form.html.erb
<%= form_for(bug) do |f| %>
  <% if bug.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bug.errors.count, "error") %> prohibited this bug from being saved:</h2>

      <ul>
      <% bug.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :application_token %>
    <%= f.text_field :application_token %>
  </div>


  <div class="field">
    <%= f.label :status %>
    <%= f.text_field :status %>
  </div>

  <div class="field">
    <%= f.label :priority %>
    <%= f.text_field :priority %>
  </div>

  <div class="field">
    <%= f.label :comment %>
    <%= f.text_area :comment %>
  </div>

  <div class="field">
    <%= f.label :state_id %>
    <%= f.text_field :state_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bugs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bugs</h1>

<table>
  <thead>
    <tr>
      <th>Application token</th>
      <th>Number</th>
      <th>Status</th>
      <th>Priority</th>
      <th>Comment</th>
      <th>State</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bugs.each do |bug| %>
      <tr>
        <td><%= bug.application_token %></td>
        <td><%= bug.number %></td>
        <td><%= bug.status %></td>
        <td><%= bug.priority %></td>
        <td><%= bug.comment %></td>
        <td><%= bug.state.id %></td>
        <td><%= link_to 'Show', bug %></td>
        <td><%= link_to 'Edit', edit_bug_path(bug) %></td>
        <td><%= link_to 'Destroy', bug, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bug', new_bug_path %>

app/views/bugs/new.html.erb
<h1>New Bug</h1>

<%= render 'form', bug: @bug %>

<%= link_to 'Back', bugs_path %>

app/views/bugs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Application token:</strong>
  <%= @bug.application_token %>
</p>

<p>
  <strong>Number:</strong>
  <%= @bug.number %>
</p>

<p>
  <strong>Status:</strong>
  <%= @bug.status %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @bug.priority %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @bug.comment %>
</p>

<p>
  <strong>State:</strong>
  <%= @bug.state.id %>
</p>

<%= link_to 'Edit', edit_bug_path(@bug) %> |
<%= link_to 'Back', bugs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstabugTask</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/search/search.html.erb
<h1>Bugs Search</h1>

<%= form_for search_path, method: :get do |f| %>
  <p>
    <%= f.label "Search for" %>
    <%= text_field_tag :q, params[:q] %>
    <%= submit_tag "Go", name: nil %>
  </p>
<% end %>

<ul>
  <% @bugs.each do |bug| %>
    <li>
      <h3>
        <%= bug.id %>
      </h3>
    </li>
  <% end %>
</ul>

app/views/states/_form.html.erb
<%= form_for(state) do |f| %>
  <% if state.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(state.errors.count, "error") %> prohibited this state from being saved:</h2>

      <ul>
      <% state.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :device %>
    <%= f.text_field :device %>
  </div>

  <div class="field">
    <%= f.label :os %>
    <%= f.text_field :os %>
  </div>

  <div class="field">
    <%= f.label :memory %>
    <%= f.number_field :memory %>
  </div>

  <div class="field">
    <%= f.label :storage %>
    <%= f.number_field :storage %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/states/edit.html.erb
<h1>Editing State</h1>

<%= render 'form', state: @state %>

<%= link_to 'Show', @state %> |
<%= link_to 'Back', states_path %>

app/views/states/index.html.erb
<p id="notice"><%= notice %></p>

<h1>States</h1>

<table>
  <thead>
    <tr>
      <th>Device</th>
      <th>Os</th>
      <th>Memory</th>
      <th>Storage</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @states.each do |state| %>
      <tr>
        <td><%= state.device %></td>
        <td><%= state.os %></td>
        <td><%= state.memory %></td>
        <td><%= state.storage %></td>
        <td><%= link_to 'Show', state %></td>
        <td><%= link_to 'Edit', edit_state_path(state) %></td>
        <td><%= link_to 'Destroy', state, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New State', new_state_path %>

app/views/states/new.html.erb
<h1>New State</h1>

<%= render 'form', state: @state %>

<%= link_to 'Back', states_path %>

app/views/states/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Device:</strong>
  <%= @state.device %>
</p>

<p>
  <strong>Os:</strong>
  <%= @state.os %>
</p>

<p>
  <strong>Memory:</strong>
  <%= @state.memory %>
</p>

<p>
  <strong>Storage:</strong>
  <%= @state.storage %>
</p>

<%= link_to 'Edit', edit_state_path(@state) %> |
<%= link_to 'Back', states_path %>